In [86]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [87]:
df = pd.read_csv(r'C:\code\MLproject1\Notebook\student_exam_performance_dataset (1).csv')

In [88]:
df.head()

,student_id,gender,age,parental_education,family_income,internet_access,study_environment,study_hours_per_day,attendance_rate,sleep_hours,...,online_courses_completed,tutoring,math_score,reading_score,writing_score,science_score,final_exam_score,previous_gpa,pass_fail,grade_category
0,S00001,Male,17,High School,Medium,Yes,Quiet,2.98,96.5,6.05,...,1,Yes,42.8,62.4,54.8,51.8,49.1,2.44,Fail,F
1,S00002,Female,18,High School,Low,Yes,Quiet,4.45,95.7,6.96,...,0,Yes,77.9,73.5,64.4,61.6,70.1,2.79,Pass,C
2,S00003,Male,17,High School,Medium,No,Quiet,3.75,76.0,7.02,...,4,Yes,53.5,38.3,36.3,47.1,42.2,1.49,Fail,F
3,S00004,Male,18,Bachelor,Medium,Yes,Quiet,2.03,72.6,6.23,...,4,No,28.3,23.5,32.0,39.0,31.9,1.34,Fail,F
4,S00005,Male,18,Bachelor,Medium,Yes,Quiet,5.14,87.3,8.54,...,0,No,74.7,54.9,73.6,55.5,66.4,2.60,Pass,C

In [89]:
df.columns

Index(['student_id', 'gender', 'age', 'parental_education', 'family_income',
       'internet_access', 'study_environment', 'study_hours_per_day',
       'attendance_rate', 'sleep_hours', 'social_media_hours',
       'assignment_completion_rate', 'participation_score',
       'online_courses_completed', 'tutoring', 'math_score', 'reading_score',
       'writing_score', 'science_score', 'final_exam_score', 'previous_gpa',
       'pass_fail', 'grade_category'],
      dtype='object')

In [90]:
df.drop(columns=['student_id','age','parental_education','parental_education','internet_access','study_environment','online_courses_completed','tutoring','assignment_completion_rate','previous_gpa','grade_category'],axis=1,inplace=True)

In [91]:
X = df.drop(columns=['math_score'],axis=1)
y= df['math_score']

In [92]:
X.shape

(10000, 12)

In [93]:
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

In [94]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
numeric_transformer = StandardScaler()
cat_transformer = OneHotEncoder()

In [95]:
preprocessor =ColumnTransformer (
    [
        ('OneHotEncoder',cat_transformer,cat_features),
        ('StandardScaler',numeric_transformer,num_features)
        ]
)

In [96]:
X = preprocessor.fit_transform(X)

In [97]:
X.shape

(10000, 16)

In [98]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=90)

In [99]:
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    r2 = r2_score(true,predicted)
    rmse = np.sqrt(mean_squared_error(true,predicted))
    mse = mean_squared_error(true,predicted)
    return mae,rmse,r2

In [100]:
models = {
    "LinearRegression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "k-neighbour":KNeighborsRegressor(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "XGBRegressor":XGBRegressor(),
    "CatBoostRegressor":CatBoostRegressor(),
    "AdaBoostRegressor":AdaBoostRegressor()
}
model_list=[]
r2_list=[]
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    train_mae,train_rmse,train_r2=evaluate_model(y_train,y_train_pred)
    test_mae,test_rmse,test_r2=evaluate_model(y_test,y_test_pred)
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    print("model performance for training set")
    print("RMSE:{:.4f}".format(train_rmse))
    print ("mae:{:.4f}".format(train_mae))
    print("R2:{:.4f}".format(train_r2))
    print("------------------------------------")
    print("model performance for testing set")
    print("RMSE:{:.4f}".format(test_rmse))
    print ("mae:{:.4f}".format(test_mae))
    print("R2:{:.4f}".format(test_r2))
    r2_list.append(test_r2)

    print("**"*10)
    print("\n")

LinearRegression
model performance for training set
RMSE:5.9210
mae:4.7216
R2:0.8175
------------------------------------
model performance for testing set
RMSE:5.7524
mae:4.5652
R2:0.8300
********************


Lasso
model performance for training set
RMSE:7.0689
mae:5.6502
R2:0.7399
------------------------------------
model performance for testing set
RMSE:7.0378
mae:5.5848
R2:0.7455
********************


Ridge
model performance for training set
RMSE:5.9211
mae:4.7215
R2:0.8175
------------------------------------
model performance for testing set
RMSE:5.7527
mae:4.5656
R2:0.8299
********************


k-neighbour
model performance for training set
RMSE:6.9167
mae:5.5085
R2:0.7510
------------------------------------
model performance for testing set
RMSE:8.5192
mae:6.7139
R2:0.6270
********************


DecisionTreeRegressor
model performance for training set
RMSE:0.0000
mae:0.0000
R2:1.0000
------------------------------------
model performance for testing set
RMSE:8.9183
mae:7.0874
R2:0.5913
********************


XGBRegressor
model performance for training set
RMSE:3.2111
mae:2.4528
R2:0.9463
------------------------------------
model performance for testing set
RMSE:6.2976
mae:5.0231
R2:0.7962
********************


Learning rate set to 0.056868
0:	learn: 13.3175620	total: 17ms	remaining: 17s
1:	learn: 12.8384228	total: 20.6ms	remaining: 10.3s
2:	learn: 12.4043320	total: 23.6ms	remaining: 7.84s
3:	learn: 11.9848862	total: 26.1ms	remaining: 6.5s
4:	learn: 11.6080114	total: 28.7ms	remaining: 5.71s
5:	learn: 11.2235459	total: 31.2ms	remaining: 5.17s
6:	learn: 10.8795583	total: 33.5ms	remaining: 4.75s
7:	learn: 10.5680632	total: 36.6ms	remaining: 4.54s
8:	learn: 10.2691893	total: 39ms	remaining: 4.3s
9:	learn: 9.9940873	total: 41.8ms	remaining: 4.14s
10:	learn: 9.7497602	total: 44.4ms	remaining: 3.99s
11:	learn: 9.5362056	total: 46.9ms	remaining: 3.87s
12:	learn: 9.3241249	total: 50ms	remaining: 3.79s
13:	learn: 9.1224889	total: 53.3ms	remaining: 3.75s
14:	learn: 8.9476895	total: 56.5ms	remaining: 3.71s
15:	learn: 8.7709571	total: 59.5ms	remaining: 3.66s
16:	learn: 8.6133135	total: 62.1ms	remaining: 3.59s
17:	learn: 8.4730163	total: 66.1ms	remaining: 3.61s
18:	learn: 8.3358807	total: 69.1ms	remaining: 3.57s
19:	learn: 8.2223277	total: 72.1ms	remaining: 3.53s
20:	learn: 8.1038772	total: 75.2ms	remaining: 3.5s
21:	learn: 7.9997915	total: 78.3ms	remaining: 3.48s
22:	learn: 7.9010903	total: 81.4ms	remaining: 3.46s
23:	learn: 7.8187879	total: 83.9ms	remaining: 3.41s
24:	learn: 7.7514023	total: 86.7ms	remaining: 3.38s
25:	learn: 7.6829564	total: 89.1ms	remaining: 3.34s
26:	learn: 7.6123683	total: 92.2ms	remaining: 3.32s
27:	learn: 7.5489063	total: 94.9ms	remaining: 3.29s
28:	learn: 7.4993320	total: 99.9ms	remaining: 3.34s
29:	learn: 7.4443620	total: 103ms	remaining: 3.34s
30:	learn: 7.3878313	total: 112ms	remaining: 3.5s
31:	learn: 7.3373672	total: 118ms	remaining: 3.58s
32:	learn: 7.2939251	total: 124ms	remaining: 3.62s
33:	learn: 7.2562383	total: 128ms	remaining: 3.64s
34:	learn: 7.2277397	total: 132ms	remaining: 3.64s
35:	learn: 7.1938306	total: 136ms	remaining: 3.64s
36:	learn: 7.1639708	total: 140ms	remaining: 3.63s
37:	learn: 7.1320825	total: 143ms	remaining: 3.63s
38:	learn: 7.0992634	total: 146ms	remaining: 3.6s
39:	learn: 7.0742404	total: 149ms	remaining: 3.59s
40:	learn: 7.0474655	total: 153ms	remaining: 3.57s
41:	learn: 7.0262225	total: 157ms	remaining: 3.57s
42:	learn: 7.0036629	total: 163ms	remaining: 3.63s
43:	learn: 6.9829317	total: 166ms	remaining: 3.61s
44:	learn: 6.9641569	total: 169ms	remaining: 3.59s
45:	learn: 6.9477950	total: 173ms	remaining: 3.58s
46:	learn: 6.9324684	total: 176ms	remaining: 3.56s
47:	learn: 6.9179710	total: 179ms	remaining: 3.54s
48:	learn: 6.9004008	total: 182ms	remaining: 3.54s
49:	learn: 6.8831053	total: 185ms	remaining: 3.52s
50:	learn: 6.8700447	total: 188ms	remaining: 3.5s
51:	learn: 6.8583066	total: 191ms	remaining: 3.47s
52:	learn: 6.8399774	total: 194ms	remaining: 3.46s
53:	learn: 6.8281299	total: 196ms	remaining: 3.43s
54:	learn: 6.8101833	total: 199ms	remaining: 3.42s
55:	learn: 6.7947099	total: 202ms	remaining: 3.4s
56:	learn: 6.7809327	total: 205ms	remaining: 3.39s
57:	learn: 6.7716223	total: 208ms	remaining: 3.37s
58:	learn: 6.7611679	total: 211ms	remaining: 3.36s
59:	learn: 6.7497742	total: 214ms	remaining: 3.35s
60:	learn: 6.7392367	total: 216ms	remaining: 3.33s
61:	learn: 6.7267595	total: 221ms	remaining: 3.34s
62:	learn: 6.7162467	total: 224ms	remaining: 3.33s
63:	learn: 6.7033443	total: 228ms	remaining: 3.33s
64:	learn: 6.6965246	total: 231ms	remaining: 3.32s
65:	learn: 6.6850502	total: 234ms	remaining: 3.31s
66:	learn: 6.6734131	total: 237ms	remaining: 3.3s
67:	learn: 6.6615241	total: 240ms	remaining: 3.29s
68:	learn: 6.6523275	total: 243ms	remaining: 3.27s
69:	learn: 6.6428222	total: 246ms	remaining: 3.27s
70:	learn: 6.6346384	total: 249ms	remaining: 3.25s
71:	learn: 6.6258787	total: 252ms	remaining: 3.25s
72:	learn: 6.6144492	total: 255ms	remaining: 3.24s
73:	learn: 6.6063367	total: 259ms	remaining: 3.24s
74:	learn: 6.5958813	total: 262ms	remaining: 3.23s
75:	learn: 6.5891438	total: 264ms	remaining: 3.21s
76:	learn: 6.5808359	total: 268ms	remaining: 3.21s
77:	learn: 6.5746238	total: 271ms	remaining: 3.21s
78:	learn: 6.5673603	total: 274ms	remaining: 3.2s
79:	learn: 6.5619811	total: 277ms	remaining: 3.19s
80:	learn: 6.5551709	total: 281ms	remaining: 3.18s
81:	learn: 6.5484785	total: 284ms	remaining: 3.18s
82:	learn: 6.5408498	total: 287ms	remaining: 3.17s
83:	learn: 6.5330020	total: 290ms	remaining: 3.16s
84:	learn: 6.5281963	total: 293ms	remaining: 3.15s
85:	learn: 6.5206337	total: 296ms	remaining: 3.15s
86:	learn: 6.5122363	total: 300ms	remaining: 3.14s
87:	learn: 6.5049922	total: 303ms	remaining: 3.14s
88:	learn: 6.4964387	total: 306ms	remaining: 3.13s
89:	learn: 6.4903597	total: 309ms	remaining: 3.12s
90:	learn: 6.4819587	total: 312ms	remaining: 3.12s
91:	learn: 6.4754773	total: 315ms	remaining: 3.11s
92:	learn: 6.4664404	total: 318ms	remaining: 3.1s
93:	learn: 6.4595835	total: 321ms	remaining: 3.1s
94:	learn: 6.4522878	total: 324ms	remaining: 3.09s
95:	learn: 6.4461925	total: 327ms	remaining: 3.08s
96:	learn: 6.4416419	total: 331ms	remaining: 3.08s
97:	learn: 6.4329176	total: 335ms	remaining: 3.08s
98:	learn: 6.4238503	total: 338ms	remaining: 3.08s
99:	learn: 6.4174958	total: 341ms	remaining: 3.07s
100:	learn: 6.4105520	total: 344ms	remaining: 3.06s
101:	learn: 6.4049029	total: 347ms	remaining: 3.05s
102:	learn: 6.3993697	total: 349ms	remaining: 3.04s
103:	learn: 6.3917901	total: 353ms	remaining: 3.04s
104:	learn: 6.3856530	total: 356ms	remaining: 3.04s
105:	learn: 6.3822490	total: 359ms	remaining: 3.03s
106:	learn: 6.3779840	total: 362ms	remaining: 3.02s
107:	learn: 6.3724328	total: 368ms	remaining: 3.04s
108:	learn: 6.3679542	total: 372ms	remaining: 3.04s
109:	learn: 6.3627169	total: 376ms	remaining: 3.04s
110:	learn: 6.3574285	total: 379ms	remaining: 3.03s
111:	learn: 6.3496403	total: 382ms	remaining: 3.03s
112:	learn: 6.3404436	total: 385ms	remaining: 3.02s
113:	learn: 6.3353262	total: 388ms	remaining: 3.02s
114:	learn: 6.3274815	total: 391ms	remaining: 3.01s
115:	learn: 6.3221657	total: 396ms	remaining: 3.02s
116:	learn: 6.3171478	total: 400ms	remaining: 3.02s
117:	learn: 6.3137394	total: 403ms	remaining: 3.01s
118:	learn: 6.3077024	total: 406ms	remaining: 3s
119:	learn: 6.3042202	total: 409ms	remaining: 3s
120:	learn: 6.2969963	total: 413ms	remaining: 3s
121:	learn: 6.2903133	total: 415ms	remaining: 2.99s
122:	learn: 6.2840840	total: 418ms	remaining: 2.98s
123:	learn: 6.2794025	total: 421ms	remaining: 2.97s
124:	learn: 6.2755647	total: 424ms	remaining: 2.97s
125:	learn: 6.2701135	total: 427ms	remaining: 2.96s
126:	learn: 6.2653799	total: 430ms	remaining: 2.95s
127:	learn: 6.2618904	total: 432ms	remaining: 2.94s
128:	learn: 6.2559234	total: 435ms	remaining: 2.94s
129:	learn: 6.2499217	total: 438ms	remaining: 2.93s
130:	learn: 6.2435570	total: 441ms	remaining: 2.93s
131:	learn: 6.2388488	total: 444ms	remaining: 2.92s
132:	learn: 6.2339342	total: 447ms	remaining: 2.91s
133:	learn: 6.2280104	total: 449ms	remaining: 2.9s
134:	learn: 6.2222858	total: 452ms	remaining: 2.9s
135:	learn: 6.2167980	total: 455ms	remaining: 2.89s
136:	learn: 6.2125908	total: 458ms	remaining: 2.88s
137:	learn: 6.2086262	total: 460ms	remaining: 2.88s
138:	learn: 6.2062677	total: 463ms	remaining: 2.87s
139:	learn: 6.2017473	total: 466ms	remaining: 2.86s
140:	learn: 6.1961578	total: 468ms	remaining: 2.85s
141:	learn: 6.1918742	total: 470ms	remaining: 2.84s
142:	learn: 6.1884755	total: 473ms	remaining: 2.83s
143:	learn: 6.1837331	total: 475ms	remaining: 2.83s
144:	learn: 6.1794240	total: 478ms	remaining: 2.82s
145:	learn: 6.1752393	total: 480ms	remaining: 2.81s
146:	learn: 6.1714775	total: 483ms	remaining: 2.8s
147:	learn: 6.1667128	total: 486ms	remaining: 2.8s
148:	learn: 6.1624414	total: 489ms	remaining: 2.79s
149:	learn: 6.1588258	total: 492ms	remaining: 2.79s
150:	learn: 6.1557678	total: 495ms	remaining: 2.78s
151:	learn: 6.1501016	total: 497ms	remaining: 2.77s
152:	learn: 6.1446533	total: 500ms	remaining: 2.77s
153:	learn: 6.1397051	total: 503ms	remaining: 2.76s
154:	learn: 6.1353219	total: 505ms	remaining: 2.75s
155:	learn: 6.1313194	total: 508ms	remaining: 2.75s
156:	learn: 6.1273998	total: 511ms	remaining: 2.74s
157:	learn: 6.1218141	total: 513ms	remaining: 2.73s
158:	learn: 6.1187829	total: 516ms	remaining: 2.73s
159:	learn: 6.1145699	total: 519ms	remaining: 2.72s
160:	learn: 6.1098512	total: 522ms	remaining: 2.72s
161:	learn: 6.1046192	total: 529ms	remaining: 2.73s
162:	learn: 6.1004976	total: 532ms	remaining: 2.73s
163:	learn: 6.0960600	total: 535ms	remaining: 2.73s
164:	learn: 6.0925322	total: 540ms	remaining: 2.73s
165:	learn: 6.0879373	total: 544ms	remaining: 2.73s
166:	learn: 6.0829564	total: 547ms	remaining: 2.73s
167:	learn: 6.0789264	total: 551ms	remaining: 2.73s
168:	learn: 6.0740167	total: 554ms	remaining: 2.72s
169:	learn: 6.0690367	total: 560ms	remaining: 2.73s
170:	learn: 6.0640344	total: 563ms	remaining: 2.73s
171:	learn: 6.0594911	total: 566ms	remaining: 2.72s
172:	learn: 6.0542528	total: 569ms	remaining: 2.72s
173:	learn: 6.0496908	total: 573ms	remaining: 2.72s
174:	learn: 6.0450344	total: 576ms	remaining: 2.72s
175:	learn: 6.0398716	total: 580ms	remaining: 2.72s
176:	learn: 6.0358747	total: 585ms	remaining: 2.72s
177:	learn: 6.0300323	total: 588ms	remaining: 2.71s
178:	learn: 6.0255007	total: 591ms	remaining: 2.71s
179:	learn: 6.0224833	total: 595ms	remaining: 2.71s
180:	learn: 6.0165200	total: 599ms	remaining: 2.71s
181:	learn: 6.0132768	total: 603ms	remaining: 2.71s
182:	learn: 6.0085084	total: 607ms	remaining: 2.71s
183:	learn: 6.0042276	total: 610ms	remaining: 2.71s
184:	learn: 6.0012580	total: 614ms	remaining: 2.7s
185:	learn: 5.9959304	total: 617ms	remaining: 2.7s
186:	learn: 5.9906791	total: 620ms	remaining: 2.7s
187:	learn: 5.9873226	total: 624ms	remaining: 2.69s
188:	learn: 5.9830640	total: 628ms	remaining: 2.69s
189:	learn: 5.9800021	total: 634ms	remaining: 2.7s
190:	learn: 5.9772424	total: 637ms	remaining: 2.7s
191:	learn: 5.9737349	total: 640ms	remaining: 2.69s
192:	learn: 5.9683843	total: 643ms	remaining: 2.69s
193:	learn: 5.9634389	total: 646ms	remaining: 2.68s
194:	learn: 5.9599604	total: 649ms	remaining: 2.68s
195:	learn: 5.9566562	total: 652ms	remaining: 2.67s
196:	learn: 5.9532812	total: 657ms	remaining: 2.68s
197:	learn: 5.9485998	total: 660ms	remaining: 2.67s
198:	learn: 5.9450065	total: 663ms	remaining: 2.67s
199:	learn: 5.9424255	total: 665ms	remaining: 2.66s
200:	learn: 5.9374338	total: 669ms	remaining: 2.66s
201:	learn: 5.9351224	total: 672ms	remaining: 2.65s
202:	learn: 5.9311759	total: 675ms	remaining: 2.65s
203:	learn: 5.9261773	total: 678ms	remaining: 2.65s
204:	learn: 5.9208080	total: 681ms	remaining: 2.64s
205:	learn: 5.9156818	total: 684ms	remaining: 2.64s
206:	learn: 5.9138998	total: 688ms	remaining: 2.63s
207:	learn: 5.9092321	total: 691ms	remaining: 2.63s
208:	learn: 5.9059884	total: 694ms	remaining: 2.63s
209:	learn: 5.9018691	total: 696ms	remaining: 2.62s
210:	learn: 5.8972338	total: 700ms	remaining: 2.62s
211:	learn: 5.8942145	total: 703ms	remaining: 2.61s
212:	learn: 5.8906493	total: 706ms	remaining: 2.61s
213:	learn: 5.8856732	total: 709ms	remaining: 2.6s
214:	learn: 5.8833199	total: 711ms	remaining: 2.6s
215:	learn: 5.8800008	total: 714ms	remaining: 2.59s
216:	learn: 5.8746116	total: 717ms	remaining: 2.59s
217:	learn: 5.8701495	total: 720ms	remaining: 2.58s
218:	learn: 5.8667073	total: 723ms	remaining: 2.58s
219:	learn: 5.8612976	total: 725ms	remaining: 2.57s
220:	learn: 5.8578295	total: 728ms	remaining: 2.57s
221:	learn: 5.8527989	total: 731ms	remaining: 2.56s
222:	learn: 5.8485496	total: 734ms	remaining: 2.56s
223:	learn: 5.8460544	total: 736ms	remaining: 2.55s
224:	learn: 5.8436271	total: 739ms	remaining: 2.54s
225:	learn: 5.8392180	total: 742ms	remaining: 2.54s
226:	learn: 5.8361137	total: 745ms	remaining: 2.54s
227:	learn: 5.8337364	total: 747ms	remaining: 2.53s
228:	learn: 5.8307039	total: 750ms	remaining: 2.52s
229:	learn: 5.8280209	total: 753ms	remaining: 2.52s
230:	learn: 5.8240522	total: 756ms	remaining: 2.52s
231:	learn: 5.8200837	total: 759ms	remaining: 2.51s
232:	learn: 5.8180461	total: 762ms	remaining: 2.51s
233:	learn: 5.8143388	total: 764ms	remaining: 2.5s
234:	learn: 5.8107234	total: 768ms	remaining: 2.5s
235:	learn: 5.8076083	total: 770ms	remaining: 2.49s
236:	learn: 5.8045470	total: 773ms	remaining: 2.49s
237:	learn: 5.8012476	total: 775ms	remaining: 2.48s
238:	learn: 5.7990963	total: 778ms	remaining: 2.48s
239:	learn: 5.7948488	total: 781ms	remaining: 2.47s
240:	learn: 5.7906163	total: 784ms	remaining: 2.47s
241:	learn: 5.7862306	total: 786ms	remaining: 2.46s
242:	learn: 5.7818066	total: 789ms	remaining: 2.46s
243:	learn: 5.7788722	total: 792ms	remaining: 2.45s
244:	learn: 5.7753760	total: 794ms	remaining: 2.45s
245:	learn: 5.7714910	total: 797ms	remaining: 2.44s
246:	learn: 5.7680518	total: 799ms	remaining: 2.44s
247:	learn: 5.7636217	total: 802ms	remaining: 2.43s
248:	learn: 5.7599276	total: 805ms	remaining: 2.43s
249:	learn: 5.7551851	total: 807ms	remaining: 2.42s
250:	learn: 5.7520195	total: 811ms	remaining: 2.42s
251:	learn: 5.7490247	total: 815ms	remaining: 2.42s
252:	learn: 5.7469129	total: 817ms	remaining: 2.41s
253:	learn: 5.7448097	total: 820ms	remaining: 2.41s
254:	learn: 5.7412048	total: 822ms	remaining: 2.4s
255:	learn: 5.7388703	total: 826ms	remaining: 2.4s
256:	learn: 5.7348131	total: 829ms	remaining: 2.4s
257:	learn: 5.7324246	total: 832ms	remaining: 2.39s
258:	learn: 5.7287411	total: 835ms	remaining: 2.39s
259:	learn: 5.7276051	total: 838ms	remaining: 2.38s
260:	learn: 5.7236772	total: 841ms	remaining: 2.38s
261:	learn: 5.7208593	total: 843ms	remaining: 2.38s
262:	learn: 5.7169009	total: 846ms	remaining: 2.37s
263:	learn: 5.7138195	total: 848ms	remaining: 2.37s
264:	learn: 5.7097820	total: 851ms	remaining: 2.36s
265:	learn: 5.7059951	total: 854ms	remaining: 2.36s
266:	learn: 5.7041278	total: 857ms	remaining: 2.35s
267:	learn: 5.7019005	total: 859ms	remaining: 2.35s
268:	learn: 5.6983698	total: 862ms	remaining: 2.34s
269:	learn: 5.6948878	total: 864ms	remaining: 2.34s
270:	learn: 5.6921660	total: 867ms	remaining: 2.33s
271:	learn: 5.6886677	total: 870ms	remaining: 2.33s
272:	learn: 5.6855423	total: 872ms	remaining: 2.32s
273:	learn: 5.6835448	total: 875ms	remaining: 2.32s
274:	learn: 5.6823989	total: 877ms	remaining: 2.31s
275:	learn: 5.6809331	total: 880ms	remaining: 2.31s
276:	learn: 5.6791492	total: 884ms	remaining: 2.31s
277:	learn: 5.6752881	total: 887ms	remaining: 2.3s
278:	learn: 5.6718489	total: 890ms	remaining: 2.3s
279:	learn: 5.6688382	total: 893ms	remaining: 2.29s
280:	learn: 5.6655192	total: 896ms	remaining: 2.29s
281:	learn: 5.6634383	total: 898ms	remaining: 2.29s
282:	learn: 5.6611446	total: 901ms	remaining: 2.28s
283:	learn: 5.6601953	total: 903ms	remaining: 2.28s
284:	learn: 5.6573154	total: 906ms	remaining: 2.27s
285:	learn: 5.6558066	total: 908ms	remaining: 2.27s
286:	learn: 5.6529737	total: 911ms	remaining: 2.26s
287:	learn: 5.6507751	total: 914ms	remaining: 2.26s
288:	learn: 5.6481576	total: 917ms	remaining: 2.25s
289:	learn: 5.6447576	total: 920ms	remaining: 2.25s
290:	learn: 5.6417848	total: 923ms	remaining: 2.25s
291:	learn: 5.6401922	total: 926ms	remaining: 2.24s
292:	learn: 5.6379746	total: 928ms	remaining: 2.24s
293:	learn: 5.6353943	total: 931ms	remaining: 2.24s
294:	learn: 5.6338326	total: 934ms	remaining: 2.23s
295:	learn: 5.6297395	total: 936ms	remaining: 2.23s
296:	learn: 5.6255124	total: 939ms	remaining: 2.22s
297:	learn: 5.6235527	total: 941ms	remaining: 2.22s
298:	learn: 5.6212067	total: 944ms	remaining: 2.21s
299:	learn: 5.6184928	total: 947ms	remaining: 2.21s
300:	learn: 5.6162445	total: 949ms	remaining: 2.2s
301:	learn: 5.6127227	total: 951ms	remaining: 2.2s
302:	learn: 5.6093580	total: 954ms	remaining: 2.19s
303:	learn: 5.6078446	total: 956ms	remaining: 2.19s
304:	learn: 5.6048407	total: 959ms	remaining: 2.19s
305:	learn: 5.6025318	total: 961ms	remaining: 2.18s
306:	learn: 5.5999362	total: 964ms	remaining: 2.18s
307:	learn: 5.5984948	total: 966ms	remaining: 2.17s
308:	learn: 5.5962339	total: 969ms	remaining: 2.17s
309:	learn: 5.5942726	total: 972ms	remaining: 2.16s
310:	learn: 5.5908048	total: 975ms	remaining: 2.16s
311:	learn: 5.5864142	total: 977ms	remaining: 2.15s
312:	learn: 5.5837703	total: 979ms	remaining: 2.15s
313:	learn: 5.5816132	total: 983ms	remaining: 2.15s
314:	learn: 5.5788195	total: 986ms	remaining: 2.14s
315:	learn: 5.5770295	total: 989ms	remaining: 2.14s
316:	learn: 5.5728079	total: 991ms	remaining: 2.14s
317:	learn: 5.5710844	total: 994ms	remaining: 2.13s
318:	learn: 5.5688138	total: 996ms	remaining: 2.13s
319:	learn: 5.5652809	total: 1000ms	remaining: 2.12s
320:	learn: 5.5621759	total: 1s	remaining: 2.12s
321:	learn: 5.5598824	total: 1.01s	remaining: 2.12s
322:	learn: 5.5579232	total: 1.01s	remaining: 2.11s
323:	learn: 5.5559324	total: 1.01s	remaining: 2.11s
324:	learn: 5.5543056	total: 1.01s	remaining: 2.11s
325:	learn: 5.5518855	total: 1.02s	remaining: 2.1s
326:	learn: 5.5502960	total: 1.02s	remaining: 2.1s
327:	learn: 5.5492261	total: 1.02s	remaining: 2.1s
328:	learn: 5.5465709	total: 1.02s	remaining: 2.09s
329:	learn: 5.5450667	total: 1.03s	remaining: 2.09s
330:	learn: 5.5421839	total: 1.03s	remaining: 2.08s
331:	learn: 5.5398003	total: 1.03s	remaining: 2.08s
332:	learn: 5.5377297	total: 1.04s	remaining: 2.08s
333:	learn: 5.5353355	total: 1.04s	remaining: 2.07s
334:	learn: 5.5332190	total: 1.04s	remaining: 2.07s
335:	learn: 5.5307688	total: 1.04s	remaining: 2.06s
336:	learn: 5.5284699	total: 1.04s	remaining: 2.06s
337:	learn: 5.5257221	total: 1.05s	remaining: 2.05s
338:	learn: 5.5230602	total: 1.05s	remaining: 2.05s
339:	learn: 5.5197092	total: 1.05s	remaining: 2.04s
340:	learn: 5.5179652	total: 1.05s	remaining: 2.04s
341:	learn: 5.5143435	total: 1.06s	remaining: 2.04s
342:	learn: 5.5122667	total: 1.06s	remaining: 2.03s
343:	learn: 5.5112811	total: 1.06s	remaining: 2.03s
344:	learn: 5.5093450	total: 1.06s	remaining: 2.02s
345:	learn: 5.5060273	total: 1.07s	remaining: 2.02s
346:	learn: 5.5035027	total: 1.07s	remaining: 2.01s
347:	learn: 5.5015551	total: 1.07s	remaining: 2.01s
348:	learn: 5.4999756	total: 1.07s	remaining: 2s
349:	learn: 5.4977318	total: 1.08s	remaining: 2s
350:	learn: 5.4954634	total: 1.08s	remaining: 2s
351:	learn: 5.4937809	total: 1.08s	remaining: 1.99s
352:	learn: 5.4910505	total: 1.08s	remaining: 1.99s
353:	learn: 5.4883717	total: 1.09s	remaining: 1.98s
354:	learn: 5.4858728	total: 1.09s	remaining: 1.98s
355:	learn: 5.4845597	total: 1.09s	remaining: 1.98s
356:	learn: 5.4827499	total: 1.09s	remaining: 1.97s
357:	learn: 5.4802124	total: 1.1s	remaining: 1.97s
358:	learn: 5.4785627	total: 1.1s	remaining: 1.97s
359:	learn: 5.4752132	total: 1.1s	remaining: 1.96s
360:	learn: 5.4730290	total: 1.1s	remaining: 1.96s
361:	learn: 5.4704714	total: 1.11s	remaining: 1.95s

In [101]:
pd.DataFrame(list(zip(model_list,r2_list)),columns=['Model_name','r2_score']).sort_values(by='r2_score',ascending=False)

              Model_name  r2_score
0       LinearRegression  0.829952
2                  Ridge  0.829932
6      CatBoostRegressor  0.816253
5           XGBRegressor  0.796192
7      AdaBoostRegressor  0.765269
1                  Lasso  0.745465
3            k-neighbour  0.627034
4  DecisionTreeRegressor  0.591269

In [102]:
lin = LinearRegression(fit_intercept=True)
lin = lin.fit(X_train,y_train)
y_pred = lin.predict(X_test)
score = r2_score(y_test,y_pred)*100
print("accuracy of the model is %.2f"%score)

accuracy of the model is 83.00